### ISSUE TITLE
esp-idf-sbom does no longer work with esp-idf-5.5.4 (IDFGH-17734)

### ISSUE THREAD

**Issue by fhars** [espressif/esp-idf-sbom#20]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

It should generate an sbom after you change the esp-idf version to 5.5.4 

### Actual behavior (suspected bug)

Instead, it fails with an error message.

### Error logs or terminal output

```shell
error:  Manifest in "/opt/esp-idf/esp-idf-v5.5.4/components/newlib/sbom_newlibc.yml" for "/opt/esp-idf/esp-idf-v5.5.4/components/newlib" is not valid: Key 'if' error:
check_if('LIBC_NEWLIB') raised AttributeError("module 'pyparsing' has no attribute 'exceptions'")
```

### Steps to reproduce the behavior

1. configure your project to use 5.5.4
2. run `idf.py` build
3. run `esp-idf-sbom create -o sbom.spdx build/project_description.json`

### Project release version

1.0.1 (current version installed by pip)

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

Ubuntu 22.04 LTS

### Shell

Bash

**Comment by fhrbata** [comment]
Hello @fhars, thank you for the detailed report.

It seems like a `pyparsing` version mismatch. To evaluate a manifest's `if:` condition (here `if: 'LIBC_NEWLIB'` in `newlib`'s manifest), `esp-idf-sbom` uses a pyparsing **3.x** API (`pyparsing.exceptions`). Your environment has pyparsing **2.x**, where that submodule doesn't exist, so the lookup fails with `AttributeError: module 'pyparsing' has no attribute 'exceptions'`. It's not really about esp-idf 5.5.4 itself; it's whichever Python environment `esp-idf-sbom` runs in having the older pyparsing.

Could you confirm the version you have?

```
python -c "import pyparsing; print(pyparsing.__version__)"
```

I expect it'll report a 2.x version. On Ubuntu 22.04 the system `python3-pyparsing` package is 2.4.7, and since `esp-idf-sbom` currently only requires `pyparsing>=2.2.2`, pip treats that as satisfied and never upgrades it.

**Workaround**: upgrade pyparsing to 3.x in the same environment where `esp-idf-sbom` is installed:

```
pip install -U "pyparsing>=3.0.0"
```

Alternatively, run the command inside the activated ESP-IDF Python environment (after sourcing `export.sh`), where IDF already pins pyparsing to 3.1+.

**Fix**: the tool genuinely uses pyparsing 3.x APIs, so the declared minimum is simply too low. I'll bump the requirement to `pyparsing>=3.0.0` in the next release so this combination can't occur.

Thank you again for flagging it!

**Comment by fhars** [comment]
Yes, it is a 2.x version:
```
$ python -c "import pyparsing; print(pyparsing.__version__)"
2.4.7
```
The workaround works.

**Comment by fhrbata** [comment]
Hello @fhars,

A quick update on the actual fix.

Looking more closely, raising the pyparsing requirement (as my earlier comment suggested) would not be the right approach. It is true that all currently supported ESP-IDF versions already require `pyparsing>=3.0.0`. However, `esp-idf-sbom` is also meant to be usable as a standalone tool against older ESP-IDF releases that are no longer officially supported but still ship pyparsing 2.x, such as esp-idf v4.4 (which pins `pyparsing>=2.0.3,<2.4.0`). Keeping pyparsing 2.x compatibility is a deliberate choice so the tool continues to work in those environments.

The actual cause is two pyparsing 3.x-only usages in `esp_idf_sbom/libsbom/expr.py` that slipped through an [earlier 2.x-compatibility change](https://github.com/espressif/esp-idf-sbom/commit/89a64c1febd778ed96cf2745ab63fb06f6998f53): `parse_string()` and the `pyparsing.exceptions` submodule. Both were added in pyparsing 3.0, so they raise `AttributeError` on pyparsing 2.x. The fix switches them to the camelCase API, which works on pyparsing 2.2.2 through 3.x, so the existing compatibility range is kept and the pyparsing requirement stays unchanged.

If you would like to unblock yourself right away, you can apply this two-line change to `esp_idf_sbom/libsbom/expr.py` in your installed copy (in the `evaluate()` function near the bottom):

```diff
 def evaluate(string: str) -> bool:
     try:
-        res = _expr.parse_string(string, parse_all=True)
-    except pp.exceptions.ParseException as e:
+        res = _expr.parseString(string, parseAll=True)
+    except pp.ParseException as e:
         raise RuntimeError(e)
     return _boolit(res[0])
```

The upgrade workaround from my previous comment (`pip install -U "pyparsing>=3.0.0"`) also still works on esp-idf 5.5.4, if you prefer not to edit the file.

The fix is queued for `master` and should land in the next release.

Thank you,
